### PR TITLE
Updata Chinese Simplified Translation

### PR DESCRIPTION
**Pull request by Juijote**

### CODE REVIEW

**Comment by Ratysz** [comment]
I no longer accept third-party translations to be bundled with my mods. Please create a translation mod instead. Thank you!

**Comment by Juijote** [comment]
I originally thought it was too much trouble to subscribe to two mods at the same time, so I thought it would be better to integrate the translation...

**Comment by Ratysz** [comment]
I thought so too, hence why I eagerly accepted them before. Then, over the course of literal years that I've been maintaining these mods, I discovered that translators usually don't magically come back to rework their translation when I make a breaking change. Or they do, but weeks after I've done all the releases I wanted and was done for the time, resulting in an awkward situation where I either have to make time to cut a new release (it doesn't take long, but it does take effort that I would rather use for something else), or let the translation sit in the backlog for many months, sometimes ending up outdated when I do get to it.

**Comment by Juijote** [comment]
My idea is that if the translation is integrated into the mod, even if the translation will be outdated in the future can not put the latest translation, but other players see the update can also be quickly in GitHub for subsequent translation, instead of the separate translation module in the workshop is more inefficient.

**Comment by Juijote** [comment]
Because your version updates don't have to accommodate whether the translations have been synced to the latest (I'm thinking of this from a player perspective).

**Pull request closed without merging**
